# Generated by Django 4.0.6 on 2022-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default=-1.0, max_length=100),
            preserve_default=False,
        ),
    ]
